In [1]:
print("hello world")

hello world


[Wei Zhao website](https://weizhaowz.notion.site/Wei-Zhao-6d57a70c1166484eb60bb6dae5cec7ba)

```Python
import math
print("Hello")
print(math.pi)```

用Python做数据分析离不开两个最常用的库，numpy(Numerical Python)和pandas.Numpy是很多数据或科学相关Python包的基础，包括Pandas。Numpy里最核心的数据结构叫ND array，意思为n维数组。一个一维数组和python的内置list很相似。不同之处在于，numpy数组里的数据类型需要统一， 例如全是数字或者全是字符串。但是list没有这个要求。Numpy是第三方库，需要import

In [1]:
import numpy as np

创建一个数组，最直观的方法就是通过numpy的array方法，把列表转换成数组。
数组对象的属性：1，ndim返回数组的维度。2shape会返回一个元祖，表示各个维度的元素的个数。3，size返回数组里面元素的总个数。4， dtype返回数组元素的类型。
除了通过array方法手动传入元素值创建数组np.array()。numpy也提供了其它一些创造数组的方法， np.ones(5), np.arange(5,10,2)和range方法类似

In [4]:
arr1=np.array([6,2,-7,2,8,-2,1])
arr1

array([ 6,  2, -7,  2,  8, -2,  1])

In [6]:
arr2=np.array([[1,3,5], [2,4,6]])
arr2

array([[1, 3, 5],
       [2, 4, 6]])

In [9]:
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)

1
(7,)
7
int64
2
(2, 3)
6
int64


In [10]:
arr_all_0=np.zeros(6)
arr_all_0

array([0., 0., 0., 0., 0., 0.])

In [11]:
arr_all_1=np.ones(6)
arr_all_1

array([1., 1., 1., 1., 1., 1.])

In [12]:
arr_even=np.arange(10,21,2)
arr_even

array([10, 12, 14, 16, 18, 20])

concatenate连接数组.
np.sort返回排序好的新数组，但是传入的原始数组不会被改变。
arr1.sort()会直接在该数组上进行改动。
numpy数组的强项之一是运算。用数组极其简单但用list不方便的是：根据特定条件从数组中筛选出值。arr[arr>6]

In [15]:
arr1=np.array([5,17,3,26,31])
arr2=np.zeros(2)
arr3=np.ones(3)
arr4=np.concatenate([arr1,arr2,arr3])
arr4

array([ 5., 17.,  3., 26., 31.,  0.,  0.,  1.,  1.,  1.])

In [16]:
arr5=arr4[arr4>6]
arr5

array([17., 26., 31.])

In [17]:
arr1=np.array([1,3,2,4,9])
arr2=np.ones(5)
arr3=np.zeros(3)
arr4=np.concatenate([arr1,arr2,arr3])
arr4

array([1., 3., 2., 4., 9., 1., 1., 1., 1., 1., 0., 0., 0.])

In [19]:
arr1.sort()
arr1

array([1, 2, 3, 4, 9])

In [21]:
print(arr1[2])
print(arr1[-3])

3
3


In [24]:
print(arr1[1:4])

[2 3 4]


In [25]:
print(arr1+arr2)

[ 2.  3.  4.  5. 10.]


In [26]:
arr1*-5

array([ -5, -10, -15, -20, -45])

In [28]:
print(arr1.max())
print(arr1.min())
print(arr1.sum())
print(arr1.mean())

9
1
19
3.8


In [31]:
arr1[arr1<1]

array([], dtype=int64)

In [32]:
arr1[arr1>3]

array([4, 9])

In [34]:
arr1[(arr1<1)|(arr1>3)]

array([4, 9])

pandas是基于numpy的。 新的数据分析库pandas。既然都有bumpy这个专门针对计算用的库，为啥还要学pandas？pandas的优点在于，由于它是构建在numpy之上的，所以继承了numpy高性能的数组计算功能，同时它还提供了更多复杂精细的数据处理功能。

In [163]:
import pandas as pd
import numpy as np

pandas提供了更好的索引取值或切片方法。
loc:表示用标签索引去取值或切片
iloc：表示用原始位置索引去取值或切片

In [38]:
s1=pd.Series([-1.2, 3.7, 2.5, -8.2, 6.3])
s1

0   -1.2
1    3.7
2    2.5
3   -8.2
4    6.3
dtype: float64

In [42]:
print(s1.index)
print(s1.values)

RangeIndex(start=0, stop=5, step=1)
[-1.2  3.7  2.5 -8.2  6.3]


In [44]:
s2=pd.Series([1,2,3,4,5], index=[5,4,3,2,1])
s2

5    1
4    2
3    3
2    4
1    5
dtype: int64

In [47]:
#按位置排序排在第2个的元素
s2.iloc[1]

2

In [48]:
#输出s2里按标签对应从5到3（包括3）范围内的元素
s2.loc[5:3]

5    1
4    2
3    3
dtype: int64

In [49]:
s3=pd.Series({"小李":82, "小陈":93, "小张":91, "小曾": 78,"小邓": 68})
s3

小李    82
小陈    93
小张    91
小曾    78
小邓    68
dtype: int64

In [51]:
s3.loc["小张"]=95
s3

小李    82
小陈    93
小张    95
小曾    78
小邓    68
dtype: int64

In [52]:
s3[s3>80]

小李    82
小陈    93
小张    95
dtype: int64

In [53]:
s3[s3<90]

小李    82
小曾    78
小邓    68
dtype: int64

In [56]:
s3[(s3>80) & (s3<90)]

小李    82
dtype: int64

series之间的运算会自动进行索引对齐，只有当某个索引同时出现在两个series里时，结果里才会有对应的值。如果希望给缺失的值一个默认值的话，可以用方法而不是用符号去做这些操作，然后给fill_value这个参数传入一个值，用符号的话我们没办法额外传参。比如从+符号改为用add方法。
Describe方法，这是数组没有的。

如何对series里每一个元素都运用这个函数，得到对应结果组成的新series
apply： apply方法并不改变原始series
除了传入定义好的函数名，在函数逻辑比较简单的时候，还可以使用匿名函数。能定义出来的函数，我们都可以作用在series的各个元素上，得到新的series

In [58]:
def get_grade_from_score(score):
    if score>=90:
        return "A"
    elif score>=80:
        return "B"
    elif score>=70:
        return "C"
    else:
        return "D"
grades=s3.apply(get_grade_from_score)
grades
squared_score=s3.apply(lamda x: x*x)
squared_score

小李    B
小陈    A
小张    A
小曾    C
小邓    D
dtype: object

In [61]:
s1=pd.Series([92,67,70,88,76], index=["小明", "小红", "小杰", "小丽", "小华"])
s2=pd.Series([95,85,60,79,76], index=["小明","小杰","小宇","小娟","小彤"])
print(s1)
print(s2)

小明    92
小红    67
小杰    70
小丽    88
小华    76
dtype: int64
小明    95
小杰    85
小宇    60
小娟    79
小彤    76
dtype: int64


In [62]:
s1+s2

小丽      NaN
小华      NaN
小娟      NaN
小宇      NaN
小彤      NaN
小明    187.0
小杰    155.0
小红      NaN
dtype: float64

In [63]:
s1.add(s2)

小丽      NaN
小华      NaN
小娟      NaN
小宇      NaN
小彤      NaN
小明    187.0
小杰    155.0
小红      NaN
dtype: float64

In [64]:
s1.add(s2, fill_value=0)

小丽     88.0
小华     76.0
小娟     79.0
小宇     60.0
小彤     76.0
小明    187.0
小杰    155.0
小红     67.0
dtype: float64

In [65]:
print(s1.describe())

count     5.000000
mean     78.600000
std      10.990905
min      67.000000
25%      70.000000
50%      76.000000
75%      88.000000
max      92.000000
dtype: float64


In [66]:
s1=s1+5
s1

小明    97
小红    72
小杰    75
小丽    93
小华    81
dtype: int64

In [67]:
s1.apply(get_grade_from_score)

小明    A
小红    C
小杰    C
小丽    A
小华    B
dtype: object

DataFrame: 多个series组成的DataFrame，不同列可以是不同数据类型。而不是像numpy二维数组那样要求数据类型全部保持一致。
获取DataFrame的所有索引可以用index属性，获取所有列名可用column属性，这些索引值的类型都是pandas库的index类。要获取所有的值，用values属性，返回的类型是numpy数组，所有针对numpy数组的操作都可以用在values属性上。

In [69]:
name=pd.Series(["小陈", "小李", "小王", "小张", "小赵", "小周"], index=["001", "002", "003", "004", "005", "006"])
gender=pd.Series(["女", "女", "男", "男", "女", "男"], index=["006", "005", "004", "003", "002", "001"])
height=pd.Series([172.5, 168.0, 178.2, 181.3, 161.7], index=["001", "002", "003", "004", "005"])

In [94]:
students=pd.DataFrame({"姓名":name, "性别": gender, "身高": height})
students

姓名 性别     身高
001  小陈  男  172.5
002  小李  女  168.0
003  小王  男  178.2
004  小张  男  181.3
005  小赵  女  161.7
006  小周  女    NaN

In [77]:
print(students.index)
print(students.columns)
print(students.values)
print(students.T)

Index(['001', '002', '003', '004', '005', '006'], dtype='object')
Index(['姓名', '性别', '身高'], dtype='object')
[['小陈' '男' 172.5]
 ['小李' '女' 168.0]
 ['小王' '男' 178.2]
 ['小张' '男' 181.3]
 ['小赵' '女' 161.7]
 ['小周' '女' nan]]
      001    002    003    004    005  006
姓名     小陈     小李     小王     小张     小赵   小周
性别      男      女      男      男      女    女
身高  172.5  168.0  178.2  181.3  161.7  NaN
001    172.5
002    168.0
003    178.2
004    181.3
005    161.7
006      NaN
Name: 身高, dtype: float64


In [78]:
print(students["身高"])

001    172.5
002    168.0
003    178.2
004    181.3
005    161.7
006      NaN
Name: 身高, dtype: float64


In [81]:
print(students[["身高", "性别"]])

        身高 性别
001  172.5  男
002  168.0  女
003  178.2  男
004  181.3  男
005  161.7  女
006    NaN  女


In [82]:
students.loc["003"]

姓名       小王
性别        男
身高    178.2
Name: 003, dtype: object

In [83]:
students.loc["003":"005"]

姓名 性别     身高
003  小王  男  178.2
004  小张  男  181.3
005  小赵  女  161.7

In [84]:
students.loc["005", "身高"]

161.7

In [85]:
students.loc[["003", "005"], ["身高", "姓名"]]

身高  姓名
003  178.2  小王
005  161.7  小赵

In [86]:
students.loc[["003","005"],:]

姓名 性别     身高
003  小王  男  178.2
005  小赵  女  161.7

In [100]:
students[(students["身高"]>165) & (students["性别"]=="女")]

姓名 性别     身高
002  小李  女  168.0

In [103]:
students.head()

姓名 性别     身高
001  小陈  男  172.5
002  小李  女  168.0
003  小王  男  178.2
004  小张  男  181.3
005  小赵  女  161.7

In [109]:
student_data={
    "001":{"姓名":"小陈", "考试1":85, "考试2": 95, "考试3": 92},
    "002":{"姓名":"小李", "考试1":91, "考试2": 92, "考试3": 94},
    "003":{"姓名":"小王", "考试1":86, "考试2": 81, "考试3": 89},
    "004":{"姓名":"小张", "考试1":79, "考试2": 89, "考试3": 95},
    "005":{"姓名":"小赵", "考试1":96, "考试2": 91, "考试3": 91},
    "006":{"姓名":"小周", "考试1":81, "考试2": 89, "考试3": 92}
}
students=pd.DataFrame(student_data)
students

001 002 003 004 005 006
姓名   小陈  小李  小王  小张  小赵  小周
考试1  85  91  86  79  96  81
考试2  95  92  81  89  91  89
考试3  92  94  89  95  91  92

In [112]:
students=pd.DataFrame(student_data).T
students

姓名 考试1 考试2 考试3
001  小陈  85  95  92
002  小李  91  92  94
003  小王  86  81  89
004  小张  79  89  95
005  小赵  96  91  91
006  小周  81  89  92

In [114]:
students["考试4"]=[72,69,79,83,82,76]
students

姓名 考试1 考试2 考试3  考试4
001  小陈  85  95  92   72
002  小李  91  92  94   69
003  小王  86  81  89   79
004  小张  79  89  95   83
005  小赵  96  91  91   82
006  小周  81  89  92   76

In [116]:
students.loc["007"]=["小杨", 79, 82, 81, 69]
students

姓名 考试1 考试2 考试3  考试4
001  小陈  85  95  92   72
002  小李  91  92  94   69
003  小王  86  81  89   79
004  小张  79  89  95   83
005  小赵  96  91  91   82
006  小周  81  89  92   76
007  小杨  79  82  81   69

In [118]:
students.drop(["006", "007"], axis=0)

姓名 考试1 考试2 考试3  考试4
001  小陈  85  95  92   72
002  小李  91  92  94   69
003  小王  86  81  89   79
004  小张  79  89  95   83
005  小赵  96  91  91   82

In [119]:
students

姓名 考试1 考试2 考试3  考试4
001  小陈  85  95  92   72
002  小李  91  92  94   69
003  小王  86  81  89   79
004  小张  79  89  95   83
005  小赵  96  91  91   82
006  小周  81  89  92   76
007  小杨  79  82  81   69

In [120]:
students.drop(["考试2","考试4"], axis=1)

姓名 考试1 考试3
001  小陈  85  92
002  小李  91  94
003  小王  86  89
004  小张  79  95
005  小赵  96  91
006  小周  81  92
007  小杨  79  81

In [121]:
students

姓名 考试1 考试2 考试3  考试4
001  小陈  85  95  92   72
002  小李  91  92  94   69
003  小王  86  81  89   79
004  小张  79  89  95   83
005  小赵  96  91  91   82
006  小周  81  89  92   76
007  小杨  79  82  81   69

In [123]:
bonus=pd.Series([2, 3, 2, 5], index=["考试1", "考试2", "考试3", "考试4"])
bonus

考试1    2
考试2    3
考试3    2
考试4    5
dtype: int64

In [124]:
bonus=pd.Series({"考试1":2, "考试2":3,"考试3": 2, "考试4": 5})
bonus

考试1    2
考试2    3
考试3    2
考试4    5
dtype: int64

In [132]:
bonus+students[["考试1", "考试2","考试3", "考试4"]]

考试1 考试2 考试3  考试4
001  87  98  94   77
002  93  95  96   74
003  88  84  91   84
004  81  92  97   88
005  98  94  93   87
006  83  92  94   81
007  81  85  83   74

In [134]:
students

姓名 考试1 考试2 考试3  考试4
001  小陈  85  95  92   72
002  小李  91  92  94   69
003  小王  86  81  89   79
004  小张  79  89  95   83
005  小赵  96  91  91   82
006  小周  81  89  92   76
007  小杨  79  82  81   69

In [135]:
students["考试4"]=students["考试4"]+10

In [136]:
students

姓名 考试1 考试2 考试3  考试4
001  小陈  85  95  92   82
002  小李  91  92  94   79
003  小王  86  81  89   89
004  小张  79  89  95   93
005  小赵  96  91  91   92
006  小周  81  89  92   86
007  小杨  79  82  81   79

DataFrame的apply和applymap方法，都是接受函数，区别在于
传给apply的函数会被运用在每列或每行上
传给applymap的函数会被运用在每个元素上
都是返回新的DataFrame原始的DataFrame没有被改变


In [137]:
student_data={
    "001":{"姓名":"小陈", "考试1":85, "考试2": 95, "考试3": 92},
    "002":{"姓名":"小李", "考试1":91, "考试2": 92, "考试3": 94},
    "003":{"姓名":"小王", "考试1":86, "考试2": 81, "考试3": 89},
    "004":{"姓名":"小张", "考试1":79, "考试2": 89, "考试3": 95},
    "005":{"姓名":"小赵", "考试1":96, "考试2": 91, "考试3": 91},
    "006":{"姓名":"小周", "考试1":81, "考试2": 89, "考试3": 92}
}
students=pd.DataFrame(student_data).T
students


姓名 考试1 考试2 考试3
001  小陈  85  95  92
002  小李  91  92  94
003  小王  86  81  89
004  小张  79  89  95
005  小赵  96  91  91
006  小周  81  89  92

In [152]:
student_grades=students[["考试1","考试2","考试3"]].mean(axis=1)
print(student_grades)
students["平均分"]=student_grades
students

001    90.666667
002    92.333333
003    85.333333
004    87.666667
005    92.666667
006    87.333333
dtype: object


姓名 考试1 考试2 考试3        平均分
001  小陈  85  95  92  90.666667
002  小李  91  92  94  92.333333
003  小王  86  81  89  85.333333
004  小张  79  89  95  87.666667
005  小赵  96  91  91  92.666667
006  小周  81  89  92  87.333333

In [157]:
average=students.loc[:,"考试1":"考试3"].mean(axis=1)
print(average)
name=students["姓名"]
print(name)
student_average=pd.DataFrame({"姓名":name, "平均分": average})
#根据字典去创建是允许我们去指定列名的。
student_average

001    90.666667
002    92.333333
003    85.333333
004    87.666667
005    92.666667
006    87.333333
dtype: object
001    小陈
002    小李
003    小王
004    小张
005    小赵
006    小周
Name: 姓名, dtype: object


姓名        平均分
001  小陈  90.666667
002  小李  92.333333
003  小王  85.333333
004  小张  87.666667
005  小赵  92.666667
006  小周  87.333333

输出每次考试第二高的分数组成的series，可以尝试结合匿名函数.

In [167]:
students.loc[:, "考试1":"考试3"].apply(lambda x: np.sort(x)[-2], axis=0)

考试1    91
考试2    92
考试3    94
dtype: int64

In [177]:
student_average
def score_grade(average_score):
    if average_score>=95:
        return "A+"
    elif 90<= average_score <95:
        return "A"
    elif 85 <= average_score <90:
        return "B+"
    elif 80<= average_score <85:
        return "B"
    elif 75<= average_score <80:
        return "C+"
    else:
        return "C"
score_grade=student_average.loc[:,"平均分"].apply(score_grade)
name=students["姓名"]
score_dengji=pd.DataFrame({"姓名": name, "等级": score_grade})
score_dengji

姓名  等级
001  小陈   A
002  小李   A
003  小王  B+
004  小张  B+
005  小赵   A
006  小周  B+

In [189]:
def get_grade(score):
    if score>=95:
        return "A+"
    elif 90<= score <95:
        return "A"
    elif 85 <= score <90:
        return "B+"
    elif 80<= score <85:
        return "B"
    elif 75<= score <80:
        return "C+"
    else:
        return "C"
get_score_grade=students.loc[:, "考试1":"考试3"].applymap(get_grade)
name=students["姓名"]
get_score_grade["姓名"]=name
get_score_grade

考试1 考试2 考试3  姓名
001  B+  A+   A  小陈
002   A   A   A  小李
003  B+   B  B+  小王
004  C+  B+  A+  小张
005  A+   A   A  小赵
006   B  B+   A  小周

In [191]:
students.describe()

姓名  考试1  考试2  考试3        平均分
count    6    6    6    6   6.000000
unique   6    6    5    5   6.000000
top     小陈   85   89   92  90.666667
freq     1    1    2    2   1.000000

In [192]:
students["考试1"]

001    85
002    91
003    86
004    79
005    96
006    81
Name: 考试1, dtype: object

In [196]:
students["考试1"]=students["考试1"].astype("int")
students["考试2"]=students["考试2"].astype("int")
students["考试3"]=students["考试3"].astype("int")
students.describe()

考试1        考试2        考试3
count   6.000000   6.000000   6.000000
mean   86.333333  89.500000  92.166667
std     6.314006   4.722288   2.136976
min    79.000000  81.000000  89.000000
25%    82.000000  89.000000  91.250000
50%    85.500000  90.000000  92.000000
75%    89.750000  91.750000  93.500000
max    96.000000  95.000000  95.000000

获取数据集：爬虫，api等。爬虫： 常见的获取数据的方法。第一，通过发送请求获取网页源代码。第二，解析网页源代码内容，提取出想要的内容，然后这些数据就可以作为后续分析的原料了。API: application programming interface 应用程序编程接口，API定义了两个程序之间的服务合约，即双方是如何使用请求和响应来进行通讯的。爬虫时，发送请求后获取的是网页源码。

JSON: JavaScript Object Notation
JSON有两种数据结构： 对象和数组可分别被转换成Python字典和列表。

In [ ]:
#JSON对象
{
    "id":"1",
    "type":"article",
    "title":"working with JSON data",
    "created":"2099-12-18T14:56:29.00Z"
}
#JSON数组
[
    {
        "title":"A light in the Attic",
        "price": "51.77"
    },
    {
        "title":"Tipping the Velvet",
        "price": "53.74"
    }
]
#只能是字符串作为Key
[
    {"键一": 1, 
    "键二":[true, 3]},
    3.14,[null, null], true
]


如何read in Json文件
pd.read_json()

csv：comma seperated values 
pd.read_csv("path", index_col="player_id")自己定义索引
pd.set_option("display.max_columns", 150)最多展示150列
pd.set_option("display.max_colwidth", 500)每列里的值最多包含几个字符
df1.tail（）输出最后几行
df1.info()
def1.describe()

In [197]:
df=pd.read_csv("/Users/weizhao/Desktop/Python/pythonProject/林粒粒python/course-documents/13 项目5：CSV数据分析智能工具/house_price.csv")

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

评估数据：结构和内容
整洁数据的特点：1， 每列是一个变量。2，每行是一个观察值。3，每个单元格是一个值
整洁数据并不是方便人类理解，而是让代码更高效处理和达成分析目的的。清理数据的目的是为了后续更高效地用程序处理数据，而不是更方便的让人类理解。
Pandas会自动忽略空缺值

评估丢失数据： isnull().sum() 得到某列/各列空缺值的数量
评估重复数据：duplicated()
duplicated(subset=["学号","性别"])是否存在重复的多个变量
评估不一致数据：value_counts()
评估无效/错误数据：sort_value()
describe()

数据的索引或者列名乱七八糟，用DataFrame的rename方法，进行重新命名。
def1.rename(index={"-2":"2", "_5":"5", "6*":"6"})
def1.rename(columns={"客户_姓名":"客户姓名", "客户 性别": "客户性别", "age":"客户年龄"})
rename除了可传入字典，还可以传入一个针对Series的函数或方法,可以是pandans库里面的，也可以是我们自行定义的
def2.rename(index=某函数/方法)
def2.rename(index=str.upper)把所有列名变成大写
str是Series类自带的一个属性，会返回一个包含了很多字符串相关操作方法的stringMethods类的实例。对这个StringMethods实例调用upper方法。
pandas.Series.str
把某列的设置为索引：
df2.set_index("Salesperson")
df3.reset_index()索引重新设置为初始默认的
对索引和列名重新排序：
df4.sort_index()
都不会改变原始的DataFrame。inplace=True


对列进行拆分：
“28.53万人/0.87平方公里” 针对python字符串，可用split方法. “28.53万人/0.87平方公里”.split("/") 可得到 ['28.53万人', '0.87平方公里']
Series也有一个能达到类似效果的方法：Series的str属性会返回一个包含很多字符串操作方法的类实例
df2[["人口", “面积”]]=df2[“人口密度”].str.split("/", expand=True)
把不同的列合并成一列：
df3[“姓”].str.cat(df3[“名”], sep="-")指定拼接时的分隔符
把宽数据转换成长数据：把一部分列名的值转换为变量的值
pd.melt(df4,id_vars=["国家代码","年份"], var_name='年龄组', value_name='肺结核病例数')
对行进行拆分：
df5.explode("课程列表")

清理数据的内容性问题：
对整列缺失值进行填充：
df2.loc["003", "销售额"]=800
能用loc或iloc提取出来的部分都可以通过附值来填充或替换值。这需要自行定位缺失值的位置。
自动找到缺失值进行填充
df4["B"].fillna(df["B"].mean())
df4.fillna(0)
df4.fillna({'A':0, 'B':10, 'C':20})把不同列的空缺值替换成不同值的效果
删除有缺失值的数据
df5.dropna()只要某行任何一个值是空缺的，就会被drop掉
df5.dropna(subset=["工资"]) 只看工资这一列有无缺失，工资缺失则删除整行
删除重复数据：
df6.drop_duplicates()只有当所有变量都相同时才会被视为重复
df6.drop_duplicates(subsets=['姓名'， ‘性别’])姓名和性别重复就删除
对值进行替换：
df7.replace(["清华"，“五道口职业技术学校”， “Tsinghua University”]， “清华大学”)
对值的类型进行转换：
s1.astype(int)
python字符串会以object这个类型名字来表示
分类数据：有限的性别种类。category
s1.astype("category")

df1.to_csv("path")将DataFrame转换为csv格式
df1.to_csv("path"， index=False)

In [207]:
original_data=pd.read_excel("/Users/weizhao/Desktop/Python/pythonProject/林粒粒python/Online Retail.xlsx")

In [208]:
original_data.head()

InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

          InvoiceDate  UnitPrice  CustomerID         Country  
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom  
1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom  
3 2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
4 2010-12-01 08:26:00       3.39     17850.0  United Kingdom

In [209]:
original_data.sample(10)

InvoiceNo StockCode                          Description  Quantity  \
289319    562264     21096      SET/6 FRUIT SALAD  PAPER PLATES         1   
412359    572285     22575         METAL MERRY CHRISTMAS WREATH         2   
512832    579516     23266  SET OF 3 WOODEN STOCKING DECORATION         7   
39780     539708    15056N            EDWARDIAN PARASOL NATURAL         1   
186395    552857    85132A         CHARLIE + LOLA BISCUITS TINS         1   
400593    571322    85099C       JUMBO  BAG BAROQUE BLACK WHITE        10   
78731     542895    85123A   WHITE HANGING HEART T-LIGHT HOLDER         3   
40833     539744     22460       EMBOSSED GLASS TEALIGHT HOLDER         3   
300577    563205     22274                 FELTCRAFT DOLL EMILY         1   
528647    580729     23541           WALL ART CLASSIC PUDDINGS          1   

               InvoiceDate  UnitPrice  CustomerID         Country  
289319 2011-08-03 16:14:00       0.83         NaN  United Kingdom  
412359 2011-10-23 12:16:00       1.95     14698.0  United Kingdom  
512832 2011-11-29 17:52:00       1.25     17841.0  United Kingdom  
39780  2010-12-21 12:18:00      12.72         NaN  United Kingdom  
186395 2011-05-11 15:34:00       5.79         NaN  United Kingdom  
400593 2011-10-17 11:05:00       2.08     13534.0  United Kingdom  
78731  2011-02-01 13:47:00       2.95     14549.0  United Kingdom  
40833  2010-12-21 15:21:00       2.51         NaN  United Kingdom  
300577 2011-08-14 12:03:00       2.95     14040.0  United Kingdom  
528647 2011-12-05 17:24:00      16.63         NaN  United Kingdom

In [210]:
original_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype         
---  ------       --------------   -----         
 0   InvoiceNo    541909 non-null  object        
 1   StockCode    541909 non-null  object        
 2   Description  540455 non-null  object        
 3   Quantity     541909 non-null  int64         
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64       
 6   CustomerID   406829 non-null  float64       
 7   Country      541909 non-null  object        
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB


In [218]:
#评估缺失数据
print(original_data.isnull().sum())
print(original_data["Description"].isnull())
original_data[original_data["Description"].isnull()]
original_data[(original_data["Description"].isnull()) & (original_data["UnitPrice"] != 0)]

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64
0         False
1         False
2         False
3         False
4         False
          ...  
541904    False
541905    False
541906    False
541907    False
541908    False
Name: Description, Length: 541909, dtype: bool


Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

In [220]:
original_data.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...  
541904    False
541905    False
541906    False
541907    False
541908    False
Length: 541909, dtype: bool

In [223]:
original_data["Country"].value_counts()

Country
United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58


In [224]:
original_data.describe()

Quantity                    InvoiceDate      UnitPrice  \
count  541909.000000                         541909  541909.000000   
mean        9.552250  2011-07-04 13:34:57.156386048       4.611114   
min    -80995.000000            2010-12-01 08:26:00  -11062.060000   
25%         1.000000            2011-03-28 11:34:00       1.250000   
50%         3.000000            2011-07-19 17:17:00       2.080000   
75%        10.000000            2011-10-19 11:27:00       4.130000   
max     80995.000000            2011-12-09 12:50:00   38970.000000   
std       218.081158                            NaN      96.759853   

          CustomerID  
count  406829.000000  
mean    15287.690570  
min     12346.000000  
25%     13953.000000  
50%     15152.000000  
75%     16791.000000  
max     18287.000000  
std      1713.600303

In [226]:
original_data[original_data['Quantity']<0]

InvoiceNo StockCode                       Description  Quantity  \
141      C536379         D                          Discount        -1   
154      C536383    35004C   SET OF 3 COLOURED  FLYING DUCKS        -1   
235      C536391     22556    PLASTERS IN TIN CIRCUS PARADE        -12   
236      C536391     21984  PACK OF 12 PINK PAISLEY TISSUES        -24   
237      C536391     21983  PACK OF 12 BLUE PAISLEY TISSUES        -24   
...          ...       ...                               ...       ...   
540449   C581490     23144   ZINC T-LIGHT HOLDER STARS SMALL       -11   
541541   C581499         M                            Manual        -1   
541715   C581568     21258        VICTORIAN SEWING BOX LARGE        -5   
541716   C581569     84978  HANGING HEART JAR T-LIGHT HOLDER        -1   
541717   C581569     20979     36 PENCILS TUBE RED RETROSPOT        -5   

               InvoiceDate  UnitPrice  CustomerID         Country  
141    2010-12-01 09:41:00      27.50     14527.0  United Kingdom  
154    2010-12-01 09:49:00       4.65     15311.0  United Kingdom  
235    2010-12-01 10:24:00       1.65     17548.0  United Kingdom  
236    2010-12-01 10:24:00       0.29     17548.0  United Kingdom  
237    2010-12-01 10:24:00       0.29     17548.0  United Kingdom  
...                    ...        ...         ...             ...  
540449 2011-12-09 09:57:00       0.83     14397.0  United Kingdom  
541541 2011-12-09 10:28:00     224.69     15498.0  United Kingdom  
541715 2011-12-09 11:57:00      10.95     15311.0  United Kingdom  
541716 2011-12-09 11:58:00       1.25     17315.0  United Kingdom  
541717 2011-12-09 11:58:00       1.25     17315.0  United Kingdom  

[10624 rows x 8 columns]

In [228]:
original_data[(original_data['Quantity']<0) & (original_data["InvoiceNo"].str[0] != "C")]

InvoiceNo StockCode Description  Quantity         InvoiceDate  \
2406      536589     21777         NaN       -10 2010-12-01 16:50:00   
4347      536764    84952C         NaN       -38 2010-12-02 14:42:00   
7188      536996     22712         NaN       -20 2010-12-03 15:30:00   
7189      536997     22028         NaN       -20 2010-12-03 15:30:00   
7190      536998     85067         NaN        -6 2010-12-03 15:30:00   
...          ...       ...         ...       ...                 ...   
535333    581210     23395       check       -26 2011-12-07 18:36:00   
535335    581212     22578        lost     -1050 2011-12-07 18:38:00   
535336    581213     22576       check       -30 2011-12-07 18:38:00   
536908    581226     23090     missing      -338 2011-12-08 09:56:00   
538919    581422     23169     smashed      -235 2011-12-08 15:24:00   

        UnitPrice  CustomerID         Country  
2406          0.0         NaN  United Kingdom  
4347          0.0         NaN  United Kingdom  
7188          0.0         NaN  United Kingdom  
7189          0.0         NaN  United Kingdom  
7190          0.0         NaN  United Kingdom  
...           ...         ...             ...  
535333        0.0         NaN  United Kingdom  
535335        0.0         NaN  United Kingdom  
535336        0.0         NaN  United Kingdom  
536908        0.0         NaN  United Kingdom  
538919        0.0         NaN  United Kingdom  

[1336 rows x 8 columns]

In [234]:
original_data[(original_data['Quantity']<0) & (original_data["InvoiceNo"].str[0] != "C")& (original_data["UnitPrice"]!=0)]

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

In [235]:
original_data[original_data["UnitPrice"]<0]

InvoiceNo StockCode      Description  Quantity         InvoiceDate  \
299983   A563186         B  Adjust bad debt         1 2011-08-12 14:51:00   
299984   A563187         B  Adjust bad debt         1 2011-08-12 14:52:00   

        UnitPrice  CustomerID         Country  
299983  -11062.06         NaN  United Kingdom  
299984  -11062.06         NaN  United Kingdom

In [236]:
cleaned_data=original_data.copy()

In [241]:
cleaned_data["InvoiceDate"]=pd.to_datetime(cleaned_data["InvoiceDate"])
cleaned_data["InvoiceDate"]

0        2010-12-01 08:26:00
1        2010-12-01 08:26:00
2        2010-12-01 08:26:00
3        2010-12-01 08:26:00
4        2010-12-01 08:26:00
                 ...        
541904   2011-12-09 12:50:00
541905   2011-12-09 12:50:00
541906   2011-12-09 12:50:00
541907   2011-12-09 12:50:00
541908   2011-12-09 12:50:00
Name: InvoiceDate, Length: 541909, dtype: datetime64[ns]

In [245]:
cleaned_data["CustomerID"]=cleaned_data["CustomerID"].astype(str)
cleaned_data["CustomerID"]

0         17850.0
1         17850.0
2         17850.0
3         17850.0
4         17850.0
           ...   
541904    12680.0
541905    12680.0
541906    12680.0
541907    12680.0
541908    12680.0
Name: CustomerID, Length: 541909, dtype: object

In [246]:
cleaned_data["CustomerID"]=cleaned_data["CustomerID"].str.slice(0,-2)
cleaned_data["CustomerID"]

0         17850
1         17850
2         17850
3         17850
4         17850
          ...  
541904    12680
541905    12680
541906    12680
541907    12680
541908    12680
Name: CustomerID, Length: 541909, dtype: object

In [262]:
cleaned_data.dropna(subset=["Description"], inplace=True)
#cleaned_data["Description"]                       

In [263]:
cleaned_data["Description"].isnull().sum()

0

In [269]:
cleaned_data["Country"]=cleaned_data["Country"].replace({"USA": "United State", "UK":"United Kingdom"})

In [270]:
len(cleaned_data[cleaned_data["Country"]=="USA"])

0

In [271]:
len(cleaned_data[cleaned_data["Country"]=="UK"])

0

In [275]:
cleaned_data=cleaned_data[cleaned_data["Quantity"]>=0]

In [276]:
len(cleaned_data[cleaned_data["Quantity"]<0])

0

In [280]:
cleaned_data.to_csv("Online_retail_cleaned.csv", index=False)

In [281]:
pd.read_csv("Online_retail_cleaned.csv")

/var/folders/nj/tt0mjykn4pz8vj9lbcmttwjm0000gn/T/ipykernel_5682/3024234675.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv("Online_retail_cleaned.csv")


InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
530688    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
530689    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
530690    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
530691    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
530692    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

                InvoiceDate  UnitPrice CustomerID         Country  
0       2010-12-01 08:26:00       2.55      17850  United Kingdom  
1       2010-12-01 08:26:00       3.39      17850  United Kingdom  
2       2010-12-01 08:26:00       2.75      17850  United Kingdom  
3       2010-12-01 08:26:00       3.39      17850  United Kingdom  
4       2010-12-01 08:26:00       3.39      17850  United Kingdom  
...                     ...        ...        ...             ...  
530688  2011-12-09 12:50:00       0.85      12680          France  
530689  2011-12-09 12:50:00       2.10      12680          France  
530690  2011-12-09 12:50:00       4.15      12680          France  
530691  2011-12-09 12:50:00       4.15      12680          France  
530692  2011-12-09 12:50:00       4.95      12680          France  

[530693 rows x 8 columns]